### PR TITLE
Update for Visual Studio 2022

### PR DESCRIPTION
**Pull request by ArkEcho**
Updated the Rockmargin Extension to VS 2022. Big Fan of the Extension.

Followed the Steps provided in this Article: https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022

The Extension only Supports 64-bit and therefore only 2022 and following Versions.

Disclaimer: Works on my Machine, developed and tested in Visual Studio 2022 Enterprise.

P.S: This is my first Contribution on GitHub.

### CODE REVIEW

**Comment by ArkEcho** [comment]
Hey @K1tty , did you have Time to Review?

**Comment by fhart** [comment]
Changes compiled and tested with Visual Studio 2022 Comunity.
It works on my machine too.
Thanks for the update @ArkEcho

**Comment by KingEurytus** [comment]
It works fine on my machine in Visual Studio 2022 Pro. Thanks @ArkEcho

**Comment by ArkEcho** [comment]
@K1tty can you please review this PR? If you no longer want to manage the Extension, i would publish it myself - of course giving you credit!

**Comment by marekburiak** [comment]
This is great ArkEcho, thank you for updating it.
It seems to work fine on VS 2022 Enterprise, the only thing I noticed is a red number in the middle of the scrollbar
rockmargin20221
Maybe it's just me though.

**Comment by ArkEcho** [comment]
Hey @marekburiak , thanks for your feedback! The red number appears if you are starting the extension in debug mode. I tested it, and it disappears on release build.

**Comment by HenrikHolmIT** [comment]
Noob question. I love RockMargin but I have no idea how to import this fork into my VS2022 installation. How would I go about doing that?
Got it. Downloaded with GitHub Desktop and build for Release. That also created a VSIX file. Nice. Thanks

**Comment by Wikzo** [comment]
> Noob question. I love RockMargin but I have no idea how to import this fork into my VS2022 installation. How would I go about doing that? Got it. Downloaded with GitHub Desktop and build for Release. That also created a VSIX file. Nice. Thanks

I'm in the same situation. Can you help explaining how/where you made the build?

This is what I'm seeing in GitHub for Windows:

github

**Comment by HenrikHolmIT** [comment]
> > Noob question. I love RockMargin but I have no idea how to import this fork into my VS2022 installation. How would I go about doing that? Got it. Downloaded with GitHub Desktop and build for Release. That also created a VSIX file. Nice. Thanks
> 
> I'm in the same situation. Can you help explaining how/where you made the build?
> 
> This is what I'm seeing in GitHub for Windows:
> 
> github

You downloaded to solution to a folder. Locate that folder and open the RockMargin.sln file. You can use GitHub Desktop to browse to download folder.

VS may need to install extension building components when you first open the solution. Once open just select to build to Release configuration and then there should be an installer available in the RockMargin\bin\Release folder. Now just install that and that will add it to your VS2022 installation.

image

**Comment by Wikzo** [comment]
> > > Noob question. I love RockMargin but I have no idea how to import this fork into my VS2022 installation. How would I go about doing that? Got it. Downloaded with GitHub Desktop and build for Release. That also created a VSIX file. Nice. Thanks
> > 
> > 
> > I'm in the same situation. Can you help explaining how/where you made the build?
> > This is what I'm seeing in GitHub for Windows:
> > github
> 
> You downloaded to solution to a folder. Locate that folder and open the RockMargin.sln file. You can use GitHub Desktop to browse to download folder.
> 
> VS may need to install extension building components when you first open the solution. Once open just select to build to Release configuration and then there should be an installer available in the RockMargin\bin\Release folder. Now just install that and that will add it to your VS2022 installation.
> 
> image

Thanks, I've downloaded the sln and opened it in Visual Studio 2022 and 2019. However, I get errors CS0433 in OptionKeys.cs. I think they might be related to .NET 4.8, which Visual Studio asked me to install when opening the project.

Would it be possible for your two upload the VSIX file here?

err

**Comment by Wikzo** [comment]
I also tried removing .NET 4.8 and opening the project again. Visual Studio 2022 shows me this:
vs_4-8
vs_4-8_2

**Comment by HenrikHolmIT** [comment]
Im trying to figure out a way to get you the file, Gustav. Google dont like it and my webserver seems to not accept it for downloads...

Ill get back.

**Comment by HenrikHolmIT** [comment]
Send you a message at your Gmail

**Comment by Wikzo** [comment]
> Send you a message at your Gmail

Thanks a lot, it works!

I don't know why I was having such troubles with the references in my Visual Studio :(

**Comment by Wikzo** [comment]
Hey @K1tty, I really like this extension - especially the word highlighting in the sidebar. I tried using a combination of https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.MatchMargin and https://marketplace.visualstudio.com/items?itemName=TrungKienPhan.WordHighlight-18439, but it's just not the same as RockMargin.

Since @ArkEcho already ported this to Visual Studio 2022, would it be possible to merge with this pull request?

**Comment by sleepyspider1** [comment]
Is someone going to publish this on the marketplace or what?

**Comment by aiprat** [comment]
For anyone still wondering how to get this PR build working. Just clone the ArkEcho/RockMargin.git, switch to Update_VS2022 branch and compile it once with Visual Studio 2022. The RockMargin.vsix file should be created in ...\RockMargin\bin\Debug or Release. Close any VS 2022 instance and install the vsix file. Thats it.

Many thanks @ArkEcho

**Comment by PiotrKarczmarz** [comment]
> For anyone still wondering how to get this PR build working. Just clone the ArkEcho/RockMargin.git

Lately I've featured RockMargin in [the article](https://contextkeeper.io/blog/my-top-7-visual-studio-plugins-supporting-deep-work/) about VS extensions supporting deep work. For anyone interested in the extension to try it out quickly, there is a direct link to [VSIX 2022 build](https://contextkeeper.io/public/DeepWorkPlugins/RockMargin2022.vsix) (from the article). I've compiled it from sources using PR by @ArkEcho.

**Comment by ArkEcho** [comment]
I just released the Extension on the VS Marketplace, crediting K1tty. Thanks everyone for your Feedback, have fun coding and using the Extension.
@K1tty if you want to release the ported version yourself, just contact me, i will then remove it

**Comment by hotte42** [comment]
I'm using RockMargin with VS 2017 for a couple of years now and I love it (can't think of using VS without it).
Last week I switched to VS 2022 and I was thankful that RockMargin has been ported.
Unfortunately break points (and trace points) are not shown in the bar, but bookmarks are.
What am I doing wrong?
PS: VS version is 17.4.2. I'm using Visual Assist as well.

**Comment by neofuturelabs** [comment]
@ArkEcho 

Hi, I added a pull request that I figured people following this thread would be interested in, so linking it here:
https://github.com/K1tty/RockMargin/pull/2

Feel free to incorporate the changes into the 2022 VS Marketplace version of RockScroll if you are interested.

Here's a copy of the description in the above pull request link:

--
I've been a fan of RockScroll/MetalScroll/RockMargin since one of its early iterations. One of the few issues I've had with the extension is how the default colors clash with the color theme of Visual Studio's Dark Mode. Furthermore, it's annoying to have to manually input the ARGB color settings every time after installing the extension.

So here are the two modifications I've included in this pull request (built on top of ArkEcho's VS2022 pull request "pr/1"):
- Changed the default colors and width to look good in Dark Mode. Adjusted the order of settings in the default settings code to match the actual settings order in the Options menu (to make it easier to adjust).
- Removed the Monitoring / IPLookup related code, as sending my IP address, Machine Name, and City to a random server (in Kyiv?) doesn't match my use-case for this extension. I suppose the crash-reporting code could be useful if the extension is being actively maintained (is it?), but I don't see why MonitoringService.SendPresense needs to be called in CreateMargin.

Feel free to integrate or not integrate these commits into the main branch, or any personal branches as you would like.

If anyone wants to really go above-and-beyond, adding a system to select from several default color themes would probably be ideal. Furthermore, I'm not sure why the RockMargin settings aren't properly exported/imported when backing up your Visual Studio user settings, so that might be worth looking into as well.

I uploaded the generated .vsix extension installer file here for convenience:
https://www.neofuturelabs.com/vsix/RockMargin_Dark.vsix

Screenshot
RockMargin_Dark

**Comment by ArkEcho** [comment]
@neofuturelabs 
sorry to keep you waiting, I'm just now randomly scrolling this closed PR ;)
I thought about adding support for Rockmargin, to automatically adjust the colors according to the selected VS Theme.

In your Addition, are the colors adjusted automatically or do you have to manually select them?

Feel free to create a Pull Request to the ArkEcho/RockMargin Repository. I will then update the version on the VS Marketplace.

**Comment by neofuturelabs** [comment]
@ArkEcho 
Thanks for the response!

A theme selector or more advanced functionality would be great in the future, but my addition only changes the default settings to look much better in Visual Studio's default dark theme. (plus some code cleanup and removal of the monitoring code that I mentioned)

I just submitted a Pull Request below, so it would be great if you could consider it. Thanks!
https://github.com/ArkEcho/RockMargin/pull/1

**Pull request closed without merging**
